//!
//! This module provides raw bindings to the jsmn library,
//! generated by bindgen. It is not needed for most use cases, 
//! as the more Rustic interface is provided.
//!
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

